export const GLOBAL_FETCH_REQUESTS = 'tim/App/GLOBAL_FETCH_REQUESTS'
export const GLOBAL_FETCH_REQUESTS_PENDING = 'tim/App/GLOBAL_FETCH_REQUESTS_PENDING'
export const GLOBAL_FETCH_REQUESTS_SUCCESS = 'tim/App/GLOBAL_FETCH_REQUESTS_SUCCESS'
export const GLOBAL_FETCH_REQUESTS_FAIL = 'tim/App/GLOBAL_FETCH_REQUESTS_FAIL'

export const GLOBAL_USER_LOGIN = 'tim/App/GLOBAL_USER_LOGIN'
export const GLOBAL_USER_LOGIN_PENDING = 'tim/App/GLOBAL_USER_LOGIN_PENDING'
export const GLOBAL_USER_LOGIN_SUCCESS = 'tim/App/GLOBAL_USER_LOGIN_SUCCESS'
export const GLOBAL_USER_LOGIN_FAIL = 'tim/App/GLOBAL_USER_LOGIN_FAIL'
