export const OFFERS_FETCH = 'tim/OfferPage/OFFERS_FETCH'
export const OFFERS_FETCH_PENDING = 'tim/OfferPage/OFFERS_FETCH_PENDING'
export const OFFERS_FETCH_SUCCESS = 'tim/OfferPage/OFFERS_FETCH_SUCCESS'
export const OFFERS_FETCH_FAIL = 'tim/OfferPage/OFFERS_FETCH_FAIL'
export const OFFER_NEW = 'tim/OfferPage/OFFER_NEW'
export const OFFER_NEW_PENDING = 'tim/OfferPage/OFFER_NEW_PENDING'
export const OFFER_NEW_SUCCESS = 'tim/OfferPage/OFFER_NEW_SUCCESS'
export const OFFER_NEW_FAIL = 'tim/OfferPage/OFFER_NEW_FAIL'
